[package]
name = "url_stream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2"
hyper-rustls = "0.23"
hyper = { version = "0.14"}
